# Generated by Django 5.1.7 on 2025-03-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('noche', 'Noche')], default='Mañana', max_length=10),
        ),
    ]
