# Generated by Django 5.1.7 on 2025-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caja_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
